### ISSUE TITLE
SyntaxError: Unexpected token '.'

### ISSUE THREAD

**Issue by technolefty** [chojs23/realword-exress-sequelize#1]
> realworld-express-sequelize@1.0.0 dev
> nodemon server.js

[nodemon] 2.0.20
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node server.js`
/home/james/realword-exress-sequelize/util/helpers.js:19
  if (toAppend?.author) {
               ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/james/realword-exress-sequelize/controllers/articles.js:13:5)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
[nodemon] app crashed - waiting for file changes before starting...

**Comment by chojs23** [comment]
What version of node you are using? The optional chaining operator(?.) is supported with more than node V14.

**Comment by technolefty** [comment]
Nice! I was on version 12. I am now on version 18. However now I get a different error when npm run dev

npm run dev

> realworld-express-sequelize@1.0.0 dev
> nodemon server.js

[nodemon] 2.0.20
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node server.js`
node:internal/modules/cjs/loader:1078
  throw err;
  ^

Error: Cannot find module '../models/tag'
Require stack:
- /home/james/realword-exress-sequelize/controllers/tags.js
- /home/james/realword-exress-sequelize/routes/tags.js
- /home/james/realword-exress-sequelize/server.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
    at Module._load (node:internal/modules/cjs/loader:920:27)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/home/james/realword-exress-sequelize/controllers/tags.js:1:13)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/james/realword-exress-sequelize/controllers/tags.js',
    '/home/james/realword-exress-sequelize/routes/tags.js',
    '/home/james/realword-exress-sequelize/server.js'
  ]
}

Node.js v18.15.0
[nodemon] app crashed - waiting for file changes before starting...

**Comment by chojs23** [comment]
There's a typo. I fixed it.

**Comment by technolefty** [comment]
Yes! That worked (changing tag to Tag). Thank you!

Now, however, I get a mysql access error

code: 'ER_ACCESS_DENIED_ERROR',
    errno: 1045,
    sqlState: '28000',
    sqlMessage: "Access denied for user 'root'@'localhost' (using password: YES)",
    sql: undefined

I altered the configuration in /util/database.js to contain my local mysql instance's credentials and created a database named 'conduit'. The backend api now starts (and creates tables) correctly

I think a mention in the readme of the mysql (?or other database) external dependency and / or the location of the configuration file may be helpful to others.

THANK YOU AGAIN for your rapid support and advice. Appreciate!! Please close this issue as 'resolved'.

**Comment by chojs23** [comment]
Yeah, I forgot about it! Thanks for letting me know that.
